### PR TITLE
reorgainzed index.md

### PR DESCRIPTION
**Pull request by maveraw**
Signed-off-by: maveraw <vaishrawat2020@gmail.com>

#### Documentation
 - Redefined the sigstore definition.
 -  Rearranged the data.
 - Changed the tone

### CODE REVIEW

**Review by haydentherapper — CHANGES_REQUESTED** [review]
I would recommend this PR be done in two steps. First reordering, then changing tone or updating wording. Otherwise it’s hard to review what is new and what was just reordered.

**Comment by maveraw** [comment]
> I would recommend this PR be done in two steps. First reordering, then changing tone or updating wording. Otherwise it’s hard to review what is new and what was just reordered.

Got it. Let us do it this way

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
@maveraw please modify this PR based on @haydentherapper's feedback. In the future, please open an issue so the community can discuss prior to opening a PR.

**Comment by ltagliaferri** [comment]
Any updates on this @maveraw

**Comment by ltagliaferri** [comment]
Closing due to inactivity.

**Pull request closed without merging**
