### PR TITLE
change sigstore docs to be about features not about tools.

### PR DESCRIPTION
**Pull request by jonvnadelberg**
Fix for issue #191 

#### Summary

The current arrangement of sigstore doc is somewhat haphazard and does not lend itself to easy understanding. I'm proposing a new organization of the material so it flows better with user journeys.  The main idea here is to allow people to find information based on the tasks they are trying to accomplish rather than them having to know what the various tool names mean.

TO review and test this fix, it will be necessary to build the documentation.   Follow the instructions in the README.md file in the repository to build.

Among changes made:

- Created signing and verifying sections
- removed cosign section.  
- created system configuration section for cosign install instructions
- renamed Fulcio section to "Certificate authority"
- renamed rekor section to "transparency log"
- reorded and renumbered each page to tell a better user journey and to allow additional pages later
- combined some pages so that information was more easily read
- added links back to github repositories where additional information can be found
- fixed all affected links in the doc

#### Release Note

NONE
#### Documentation

Doc only change

### CODE REVIEW

**Comment by olivekl** [comment]
Thanks, @jonvnadelberg, this is a heavy lift! To confirm: you have not edited any content at this stage, only moved, combined, or deleted? That will make review easier for this PR, as it is structural only (and editing can happen in a later PR).

For context, this PR is connected with [discussion in Issue #187](https://github.com/sigstore/docs/issues/187#issuecomment-1590055593).

**Comment by jonvnadelberg** [comment]
> Thanks, @jonvnadelberg, this is a heavy lift! To confirm: you have not edited any content at this stage, only moved, combined, or deleted? That will make review easier for this PR, as it is structural only (and editing can happen in a later PR).
> 
> For context, this PR is connected with [discussion in Issue #187](https://github.com/sigstore/docs/issues/187#issuecomment-1590055593).

Yes.   No new content, just rearranging what was already there.

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
There needs to be a config file to redirect the old links. Here's some documentation from Netlify, since that's the host for this site: https://docs.netlify.com/routing/redirects/

**Comment by jonvnadelberg** [comment]
> There needs to be a config file to redirect the old links. Here's some documentation from Netlify, since that's the host for this site: https://docs.netlify.com/routing/redirects/

I went through the entire doc set and changed each link as necessary.  So they should all be ok.  Unless this is something else that needs to be fixed?

**Comment by ltagliaferri** [comment]
> > There needs to be a config file to redirect the old links. Here's some documentation from Netlify, since that's the host for this site: https://docs.netlify.com/routing/redirects/
> 
> I went through the entire doc set and changed each link as necessary. So they should all be ok. Unless this is something else that needs to be fixed?

I only see `.md` files edited here. I mean that when a user is looking at a site that references a Sigstore page, they will land on a 404 unless we redirect them. So we need to redirect those links

**Comment by olivekl** [comment]
> 
> So this is for an outside web site that references an internal page in sigstore? Say someone in a blog someplace referencing a specific file or something?

Yes. I think this documentation should cover it: https://docs.netlify.com/routing/redirects/

**Comment by jonvnadelberg** [comment]
> > > There needs to be a config file to redirect the old links. Here's some documentation from Netlify, since that's the host for this site: https://docs.netlify.com/routing/redirects/
> > 
> > 
> > I went through the entire doc set and changed each link as necessary. So they should all be ok. Unless this is something else that needs to be fixed?
> 
> I only see `.md` files edited here. I mean that when a user is looking at a site that references a Sigstore page, they will land on a 404 unless we redirect them. So we need to redirect those links

OK, I think I understand the issue.  I'm working on it.

**Comment by jonvnadelberg** [comment]
closing PR to add _redirects file

**Pull request closed without merging**
