### PR TITLE
docs: Update index.md

### LINKED ISSUE #51: Jumbled sentence in How Sigstore Works
**Description**

Here I found one sentence which is jumbled and not creating any sense

## Current behaviour
`This checks you are who you say you are using OpenID Connect`

if we update with this might be meaningful

`This checks who you are using OpenID Connect`

Dec-12-22-01

### PR DESCRIPTION
**Pull request by ro4i7**
#### Summary
Close #51

### CODE REVIEW

**Comment by ro4i7** [comment]
@ltagliaferri  please check this, if this can be merged.

**Comment by ltagliaferri** [comment]
There is related discussion on the issue and the previous open PR https://github.com/sigstore/docs/issues/51

I suggest we rewrite this sentence completely rather than modify it at this time

**Comment by ro4i7** [comment]
> There is related discussion on the issue and the previous open PR #51
> 
> I suggest we rewrite this sentence completely rather than modify it at this time

So, should I modify the whole sentences and update this PR. Or I close this PR because there is open PR 51 for this

**Comment by ro4i7** [comment]
> > There is related discussion on the issue and the previous open PR #51
> > I suggest we rewrite this sentence completely rather than modify it at this time
> 
> So, should I modify the whole sentences and update this PR. Or I close this PR because there is open PR 51 for this

@ltagliaferri What about this,

'When you use Fulcio, Sigstore asks for a certificate from our main authority to confirm that you are the author. It uses your email address to check your identity through OpenID Connect. Fulcio then gives you a time-stamped certificate, which proves that you are signed in and that it is actually you.'

**Comment by ltagliaferri** [comment]
Let's continue the discussion on the issue #51

**Pull request closed without merging**
