### PR TITLE
Reorganized index.md

### PR DESCRIPTION
**Pull request by maveraw**
### Documentation
- Reorganized the overview page of Sigstore.
- Defined the Sigstore definition again.
- Merged "About the project" with the definition.
- Changed headings and the tone of the document (in a professional manner ).

### CODE REVIEW

**Comment by maveraw** [comment]
Can anybody tell me whts wrong?? 
I have written the commit message as directed.

" Reorganized index.md
  Signed-off-by: Vaishali <my email>"

**Comment by Neilblaze** [comment]
@maveraw The Certificate of Origin is assigned to your primary username (*maveraw*). Hence using a different GitHub account (i.e. technically a different username) should auto-reject the sign-off. I recommend you update the DCO of both of your commits to → *`maveraw <vaishaliishu08@gmail.com>`*.

I also find a few of the changes unnecessary as the present ones are concise and to the point. I'd recommend taking suggestions from @ltagliaferri to reduce reiterations while working.

**Comment by maveraw** [comment]
Got it just now

**Comment by maveraw** [comment]
@Neilblaze I think I did not got it 😅😅

**Comment by Neilblaze** [comment]
@maveraw Take your time! I'm about to head out for bed, but in case you fail to progress, feel free to drop me a text on Slack (search for Pratyay Banerjee).

**Pull request closed without merging**
