### PR TITLE
docs: Document/blog post on how UUID, EntryID, logID, logIndex differ in Rekor

### LINKED ISSUE #75: Document/blog post on how UUID, EntryID, logID, logIndex differ in Rekor
Especially wrt the updates after sharding. I have gotten questions around this.

### PR DESCRIPTION
**Pull request by ro4i7**
#### Summary
Closes #75

### CODE REVIEW

**Comment by ro4i7** [comment]
@ltagliaferri please check this, if this can be merged.

**Review by ltagliaferri — COMMENTED** [review]
This text is suspected to be machine generated or pulling text from other sources without citation

**Comment by ro4i7** [comment]
> This text is suspected to be machine generated or pulling text from other sources without citation

Ok definitely hive the citation

**Comment by haydentherapper** [comment]
Yea, this does not address the original point of the issue. We need at most a few sentences to describe these differences, this has tons of superfluous details. Please take a look at the Rekor code base and how the referenced field are used if you’re interested in completing this issue.

**Comment by ro4i7** [comment]
> Yea, this does not address the original point of the issue. We need at most a few sentences to describe these differences, this has tons of superfluous details. Please take a look at the Rekor code base and how the referenced field are used if you’re interested in completing this issue.

Yeah I am working on it.

**Comment by ltagliaferri** [comment]
Let's close this and continue the discussion on the issue (https://github.com/sigstore/docs/issues/75), starting with an outline

**Pull request closed without merging**
