### PR TITLE
Adding Python language client information.

### PR DESCRIPTION
**Pull request by hayleycd**
#### Summary
Partially addresses #324 by bringing in information about the Python Language Client

#### Release Note

None

### CODE REVIEW

**Comment by hayleycd** [comment]
@woodruffw @haydentherapper @cmurphy please see new Python PR

**Review by cmurphy — APPROVED** [review]
lgtm :+1:

**Review by haydentherapper — APPROVED** [review]
Looks great! @woodruffw for final approval

**Review by woodruffw — APPROVED** [review]
LGTM, thanks a ton @hayleycd!

**Pull request merged**
