### PR TITLE
Fix Go Module Path of sget

### LINKED ISSUE #28: Fix Go Module path of sget
**Description**

**Version**

https://docs.sigstore.dev/cosign/working_with_blobs#sget

`github.com/sigstore/cosign/cmd/sget` was deprecated, so sget outputs the following notice.

```console
$ go install github.com/sigstore/cosign/cmd/sget@latest
$ sget --help
main.go:43:
-------- NOTICE --------
The sget tool in the cosign repo is deprecated, and will be removed in a future release.

If you're interested in fetching content from an OCI registry or from an arbitrary URLs, please see: https://github.com/sigstore/sget.
------------------------
sget is DEPRECATED in the cosign repo -- see https://github.com/sigstore/sget for the new tool.
```

The correct Module path is `github.com/sigstore/sget@latest`.

```console
$ go install github.com/sigstore/sget@latest
```

### PR DESCRIPTION
**Pull request by suzuki-shunsuke**
Closes #28

#### Summary

github.com/sigstore/cosign/cmd/sget@latest was deprecated, so sget outputs the following notice.

```console
$ go install github.com/sigstore/cosign/cmd/sget@latest
$ sget --help
main.go:43:
-------- NOTICE --------
The sget tool in the cosign repo is deprecated, and will be removed in a future release.

If you're interested in fetching content from an OCI registry or from an arbitrary URLs, please see: https://github.com/sigstore/sget.
------------------------
sget is DEPRECATED in the cosign repo -- see https://github.com/sigstore/sget for the new tool.
```

### CODE REVIEW

**Comment by cpanato** [comment]
there is a notice of deprecation but that was not fully deprecated yet. So we hold this PR until the full deprecation

cc @imjasonh

**Comment by suzuki-shunsuke** [comment]
Thank you for your review.
I got it.

**Comment by lukehinds** [comment]
@imjasonh could you comment if this is good to merge?

**Comment by imjasonh** [comment]
I'd prefer to just drop any mention of `sget` from the docs completely, which will make it easier to deprecate the code in the cosign repo, and the separate repo.

**Comment by lukehinds** [comment]
@imjasonh are we deprecating github.com/sigstore/sget too? Maybe I misunderstood.

**Comment by imjasonh** [comment]
> @imjasonh are we deprecating github.com/sigstore/sget too? Maybe I misunderstood.

I think that would be best. I don't think there's any plan to continue developing it at this time.

**Comment by haydentherapper** [comment]
Closing as this has been deleted

**Pull request closed without merging**
