### PR TITLE
Embed status of public good instance

### PR DESCRIPTION
**Pull request by haydentherapper**
Small wording changes for deployment page too.

### CODE REVIEW

**Comment by haydentherapper** [comment]
Any suggestions on a better place to embed this status?

**Review by cpanato — APPROVED** [review]

**Review by ltagliaferri — COMMENTED** [review]
Maybe the status can even go on the home page? I would maybe add one line of context regardless, something like "Status of public-good instance," or "Review / check status of public-good instance"

**Comment by ltagliaferri** [comment]
@haydentherapper — any thoughts about moving this to the first page or adding the context sentence?

**Comment by haydentherapper** [comment]
Yes, sorry, haven't gotten a chance to! I'll likely do both.

**Comment by ltagliaferri** [comment]
No worries, just was not sure if you got the message or if I could help

**Comment by haydentherapper** [comment]
Do you think it would look good in the header, or just in the overview page?

**Comment by ltagliaferri** [comment]
Sorry, @haydentherapper , I think the header is fine!

**Comment by ltagliaferri** [comment]
I'll merge and we can always change it!

**Pull request merged**
