### PR TITLE
Project docs left sidebar

### LINKED ISSUE #250: Link to project-specific documentation on the left sidebar
## Description

While we have some links in the central documentation site to docs under each project, they're hard to find, especially for those who don't know the project well.

After some discussion, it's been proposed to add links to documentation maintained by each project on the left sidebar. The links will go out to each external project site. 

If anyone would like to advocate for another approach to surfacing or maintaining project-specific docs, this would be a good place to discuss. If there isn't discussion, next week I'll assign myself this issue and create a PR updating the left menu.

## Notes

References #243

### PR DESCRIPTION
**Pull request by smythp**
## Overview

This PR adds items to the left sidebar under the heading "Project Documentation." These items lead to external docs in the respective project repositories.

## Implementation

Because Hugo generates the left sidebar from metadata in the content folder (one of the three main approaches to generating menus in Hugo), adding a section that leads to external sites required writing new template logic.

This PR removes vestigial menu metadata from the menus.toeml config file and adds a new menu, "external." This menu is referenced directly in the sidebar partial when building the sidebar. Because menu items created this way have a different structure from menu items created automatically (thanks, Hugo), the logic added in this PR takes menu items defined in the config and modifies them to look like automaticly generated menu items. A new section is then created, the new pages are added to the section metadata, and the new section is appended to the site's automatically generated sections.

## Adding New Items

To edit the items in this new menu heading, future contributors should edit the toeml in `config/_default/menus/menus.en.toml`.

## Notes

This PR resolves #250

### CODE REVIEW

**Review by ltagliaferri — COMMENTED** [review]
What do you think about having these open in a new tab?

**Comment by smythp** [comment]
That makes sense to me. I pushed a commit to make the external docs open ina new tab. Regular docs pages should be unaffected.

**Review by ltagliaferri — APPROVED** [review]
I'm not seeing the change in the Netlify preview, but let's merge and see

**Comment by smythp** [comment]
Seems to be working for me on the live site. Thanks, Lisa!

**Pull request merged**
