### PR TITLE
Corrected the confusion of steps in the document due to formatting

### PR DESCRIPTION
**Pull request by normal-coder**
#### Summary

Resolves https://github.com/sigstore/docs/issues/224

improve Logging documentation. The main changes are as follows:

- Added language settings for code blocks
- Fixed wrong numbering of operation steps caused by indentation
- Corrected heading hierarchy for first paragraph

The following is a comparison example before and after restoration:

Before:

image

After:

image

Reference from specification:

- [MD009/no-trailing-spaces](https://github.com/DavidAnson/markdownlint/blob/v0.29.0/doc/md009.md)
- [MD010/no-hard-tabs](https://github.com/DavidAnson/markdownlint/blob/v0.29.0/doc/md010.md)
- [MD012/no-multiple-blanks](https://github.com/DavidAnson/markdownlint/blob/v0.29.0/doc/md012.md)
- [MD029/ol-prefix](https://github.com/DavidAnson/markdownlint/blob/v0.29.0/doc/md029.md)
- [MD031/blanks-around-fences](https://github.com/DavidAnson/markdownlint/blob/v0.29.0/doc/md031.md)
- [MD032/blanks-around-lists](https://github.com/DavidAnson/markdownlint/blob/v0.29.0/doc/md032.md)
- [MD034/no-bare-urls](https://github.com/DavidAnson/markdownlint/blob/v0.29.0/doc/md034.md)
- [MD040/fenced-code-language](https://github.com/DavidAnson/markdownlint/blob/v0.29.0/doc/md040.md)

#### Release Note

None.

#### Documentation

This PR implements the doc change.

### CODE REVIEW

**Comment by smythp** [comment]
Hi @normal-coder,

I just looked through this and it seems like a great PR.

One question I have is with the indentation of fenced (```) code blocks, for example the go and yml code blocks. Why are they indented by four spaces?

For example, I would expect:

<pre>
```go
...
```
</pre>

instead of:

<pre>
    ```go
     ...
     ```
</pre>

This doesn't seem to affect rendering, but I'd typically expect fenced code blocks to not be indented.

Thanks, this seems like a great contribution.

**Comment by smythp** [comment]
Also @ltagliaferri , this PR seems to be post-migration and doesn't need to be rebased.

**Comment by normal-coder** [comment]
> 



> Hi @normal-coder,
> 
> I just looked through this and it seems like a great PR.
> 
> One question I have is with the indentation of fenced (```) code blocks, for example the go and yml code blocks. Why are they indented by four spaces?
> 
> For example, I would expect:
> 
> ```go
> ...
> ```
> instead of:
> 
>     ```go
>      ...
>      ```
> This doesn't seem to affect rendering, but I'd typically expect fenced code blocks to not be indented.
> 
> Thanks, this seems like a great contribution.

Perhaps you should try to understand [principle of uniformity](https://spec.commonmark.org/0.30/#principle-of-uniformity) of the CommonMark specification: **if a chunk of text has a certain meaning, it will continue to have the same meaning when put into a container block (such as a list item or blockquote).**

I can understand that coding preferences don't want to have too many spaces in front of the example code snippets (which is extremely unfriendly to Vim or Emacs users), but compared to blockquotes inserting `>` at the beginning of the line, it maintains the integrity and coherence of the code sex.

Such writing does not affect rendering, because most parsers follow this specification for processing and implementation.

**Review by smythp — APPROVED** [review]
In addition to reviewing the markdown, I've tested these changes with a screen reader. The change to the heading hierarchy and to list contiguity improves accessibility. Previously, the steps were treated as seven separate lists, not one list with seven items (for example). Consistency in headings is also important for screen reader navigation.

I learned a lot reading through the spec doc you shared. Semantically, how you've done things here now makes sense to me. The code blocks are indented to show that they are part of the list item, and also to indicate that the list should not be interrupted in parsing. Thanks for the explanation.

**Pull request merged**
